---
output:
  word_document:
    reference_docx: finalStyles.docx
---

Feedback tracker - `r passDivision`
========================================================

Trust summary
--------------------------------------------------------

```{r, echo = FALSE, results = 'asis'}

panderOptions('knitr.auto.asis', TRUE)

panderOptions('table.alignment.default', function(df)
  ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

trackerData = trustData[is.na(trustData$formtype) | trustData$formtype != "carer", ]

POLookup = read.csv("poLookup.csv")

POLookup$Directorate[POLookup$TeamN == "Rampton Hospital"] = 17
POLookup$Directorate[POLookup$Directorate %in% c(4, 6, 13, 14, 24)] = 21

timetext = paste(rep(c("Apr - Jun", "Jul - Sep", "Oct - Dec", "Jan - Mar"), 10)[-40],
                 c("09", "09", "09", rep(10:18, each = 4)))

trackerData$Directorate[trackerData$Directorate %in% 8:12] = 17
trackerData$Directorate[trackerData$Directorate %in% c(4, 6, 13, 14, 24)] = 21

PO$Directorate[PO$Directorate %in% 8:12] = 17
PO$Directorate[PO$Directorate %in% c(4, 6, 13, 14, 24)] = 21

PO$TeamN = as.character(PO$TeamN)

counts$Directorate[counts$Directorate %in% 8:12] = 17
counts$Directorate[counts$Directorate %in% c(4, 6, 13, 14, 24)] = 21

Quarter = max(counts$Time, na.rm = TRUE)

trackerData = subset(trackerData, Time %in% (Quarter - 4) : Quarter)
trackerData$Time = factor(trackerData$Time, levels = (Quarter - 4) : Quarter)

poData = subset(PO, Time %in% (Quarter - 4) : Quarter)
poData$Time = factor(poData$Time, levels = (Quarter - 4) : Quarter)

### pass in the division and directorate code

theList = list("Local Partnerships - Mental Healthcare" = c(2, 7, 21),
               "Forensic division" = c(3, 5, 17, 15, 16),
               "Local Partnerships - Community Healthcare" = 
                 c(25, 26, 27, 28, 29, 30, 31, 33, 34)
)

```

This report summarises data from `r as.character(min(poData$Date))` to `r as.character(max(poData$Date))`.

This is a snapshot of the database, but it should be noted that data entry can lag for up to a month and 10 days after data are received- that is, all data will be entered and live in the database by the 10th of the month after they were received. The current quarter's data will therefore never be completely up to date but is included for interest.

Please note further that Care Opinion data is imperfectly matched from the Care Opinion database and the numbers within this report may differ substantially from the true numbers (especially at team level). Care Opinion story numbers should be read as minima, not maxima.

```{r, echo = FALSE, results = 'asis'}

trustTable = data.frame(as.numeric(rev(with(trackerData, table(Time)))), 
                        as.numeric(rev(with(poData, table(Time)))))

trustTable = rbind(trustTable, colSums(trustTable))

names(trustTable) = c("SUCE responses", "CO responses")

rownames(trustTable) = c(timetext[Quarter : (Quarter - 4)], "Total")

pandoc.table(trustTable, style='rmarkdown')

```

Divisions
--------------------------------------------------------

```{r, echo = FALSE, results = 'asis'}

# make table

combTable = as.data.frame.matrix(with(trackerData, table(Division, Time)))

poTable = as.data.frame.matrix(with(poData, table(Division, Time)))

# flip columns

combTable = combTable[, ncol(combTable) : 1]

poTable = poTable[, ncol(poTable) : 1]

# add rowSums

combTable = cbind(combTable, rowSums(combTable))

poTable = cbind(poTable, rowSums(poTable))

# combine

names(poTable) = ""
names(combTable) = ""

combTable = rbind(combTable, poTable)

# label rows

timetext = paste(rep(c("Apr - Jun", "Jul - Sep", "Oct - Dec", "Jan - Mar"), 10)[-40],
                 c("09", "09", "09", rep(10:18, each = 4)))

rownames(combTable) = paste0(rep(c("SUCE responses- ", "CO responses- "), each = 3),
                           rep(c("LP - MH", "Forensic", "LP - CH"), each = 1))

colnames(combTable) = c(timetext[Quarter : (Quarter - 4)], "Total")

pandoc.table(combTable, style='rmarkdown', emphasize.rows = 4:6, emphasize.strong.rows = 1:3)

```

```{r, echo = FALSE, results = 'asis', warning = FALSE}

for(i in theList[[passDivision]]){

# for(i in c(16)){
  
  ### this is the directorate table
  
  cat("<br>\n\n")
  
  cat("#", directorate[i], "\n")
  
  ### Using three quarters because that allows you to span the forensic 6 months
  
  mydata = subset(trackerData, TeamC != 1700 & Directorate == i)
  
  subPO = subset(poData, Directorate == i)
  
  # make table

  dirTable = data.frame(cbind(rev(with(mydata, table(Time))), rev(with(subPO, table(Time)))))
  
  dirTable = rbind(dirTable, colSums(dirTable))

  names(dirTable) = c("SUCE responses", "CO responses")
  
  rownames(dirTable) = c(timetext[Quarter : (Quarter - 4)], "Total")
  
  pandoc.table(dirTable, style='rmarkdown')
  
  cat("<br>\n\n")
  
  ### this is the team table with SUCE codes
  
  subCounts = subset(counts, Time %in% (Quarter - 4) : Quarter &
                       (Contacts > 0 | is.na(Contacts)) & Directorate %in% i)
  
  suceTab = melt(with(mydata, table(TeamC, Time)), na.rm = TRUE)
  
  poTab = with(subPO, table(TeamC, Time))
  
  if(nrow(poTab) > 0){ # if there is any PO data, fine, calculate
    
      poTab = melt(poTab, na.rm = TRUE)
    
  } else { # if not, just take the SUCE data and make everything "0"
    
    poTab = suceTab
    
    poTab$value = 0
  }
  
  firstTab = merge(suceTab, subCounts, by = c("TeamC", "Time"), all = TRUE)
  
  finalTab = merge(firstTab, poTab, by = c("TeamC", "Time"), all = TRUE)
  
  ### IF NOT FORENSIC remove teams that no longer exist
  
  if(passDivision != "Forensic division"){
    
    finalTab = finalTab[finalTab$TeamC %in% subset(subCounts, Time == Quarter)$TeamC, ]
    
    }

  ### reverse order the table by time so the most RECENT directorate code predominates
  
  finalTab = finalTab[order(finalTab$TeamC, -finalTab$Time), ]
  
  finalTab = finalTab[, c("TeamC", "TeamN", "Directorate", "value.x", "value.y", "Time")]
  
  finalTab$TeamN[is.na(finalTab$TeamN)] = as.character(
    sapply(finalTab$TeamC[is.na(finalTab$TeamN)], function(x) {
      
      theName = as.character(trackerData$TeamN[which(trackerData$TeamC == x)])
      theName = theName[!is.na(theName)]
      return(tail(theName, 1))
      
      }
      )
    )
  
  shapeTab = data.frame(reshape(finalTab, v.names = c("value.x", "value.y"), timevar = "Time",
                                idvar = "TeamC", direction = "wide"))
  
  names(shapeTab) = c("TeamC", "Team", "Directorate",
                      paste0(rep(c("SUCE: ", "CO: "), 4),
                             rep(timetext[Quarter : (Quarter - 4)], each = 2)
                             ))
  
  ### remove all the unmatched teams
  
  shapeTab = shapeTab[shapeTab$Team != "character(0)", ]
  
  finalTab = shapeTab[, !names(shapeTab) %in% c("TeamC", "Directorate")]
  
  finalTab[is.na(finalTab)] = 0
  
  ### remove the Patient Opinion data, it is not needed
  
  finalTab2 = finalTab[, c(1, 2, 4, 6, 8, 10)]
  
  rownames(finalTab) = NULL
  
  pandoc.table(finalTab, style='rmarkdown')
  
  cat("<br>\n\n")
  
  ### this is the table with the PO codes
  
  ### add factors for all the teams on the PO list
  
  # subPOLookup = POLookup[!is.na(POLookup$Directorate) & POLookup$Directorate == i, ]
  
  # poTab = data.frame(with(subPO, table(Time, factor(TeamN, levels = subPOLookup$TeamN))))
  
  uniquePO = unique(subset(subPO, Directorate == i)$TeamN)
  
  poTab = data.frame(with(subPO, table(Time, factor(TeamN, levels = uniquePO[!is.na(uniquePO)]))))
  
  # are there any PO stories matched?
  
  if(nrow(poTab) > 0){
    
    poTab = poTab[order(poTab$Var2, -as.numeric(poTab$Time)), ]
    
    shapePO = data.frame(reshape(poTab, v.names = c("Freq"), timevar = "Time",
                                 idvar = "Var2", direction = "wide"))
    
    names(shapePO) = c("Team", paste0("CO: ", timetext[Quarter : (Quarter - 4)]))
    
    rownames(shapePO) = 1 : nrow(shapePO)
    
    pandoc.table(shapePO, row.names = FALSE, style='rmarkdown')
    
    cat("<br>\n\n")
    
    } else {
      
      cat("No Care Opinion stories matched to team in the previous year\n  <br/>")
    }
  
  
  } # for i in directorates

```

