---
title: Quarterly report
output: html_document
params:
  division: NA
  directorate: NA
  team: NA
  date_from: NA
  date_to: NA
  carerSU: NA
  area_name: NA
---

<!-- So I need to declare the parameters here, and then pass them through from Shiny -->
<!-- Then I can use an observe() function with the GET string so the report is generated if -->
<!-- The parameters are set using a GET string -->

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# source the code with the functions in

source("../report_functions.R")

# calculate the date range first

today = Sys.Date()

previous_quarter <- (quarter(today)) - 1 %% 4
previous_year <- year(today)

if(previous_quarter == 0){
  
  previous_quarter <- 4
  previous_year <- previous_year - 1
}

first_date <- yq(paste0(previous_year, ": Q", previous_quarter))

end_date <- yq(paste0(year(today), ": Q", quarter(today))) - 1

# filter by area and name the areas

if(params$division != "NA"){
  
  suceData = trustData %>%
    filter(Division %in% params$division)
  
} else if(params$directorate != "NA"){
  
  suceData = trustData %>%
    filter(Directorate %in% params$directorate)
  
} else if(params$team != "NA"){
  
  suceData = trustData %>%
    filter(TeamC %in% params$team)
} else {
  
  suceData = trustData
}

# now filter by SU/ carer

if(params$carerSU == "SU"){
  
  suceData = suceData %>%
    filter(is.na(formtype) | formtype != "SUCE")
  
} else if(params$carerSU == "carer"){
  
  suceData = suceData %>%
    filter(formtype == "carer")
  
} else if(params$carerSU == "bothCarerSU"){
  
  # nothing!
}

# filter by time last and produce another dataset with 2 years in

two_year_data <- suceData %>% 
  filter(Date > end_date - 365 * 2)

suceData <- suceData %>% 
  filter(Date >= first_date, Date <= end_date)

report_information <- reportFunction(suceData)

```

## Summary

This report summarises data from `r first_date` to `r end_date`

```{r, results = "asis"}

if(is.null(report_information)){
  
  myString = "Within the selected time and area there were no responses"
} else {
  
  myString = paste0("<p>Within ", params$area_name, " in the selected time there were ", report_information[["NR"]],
                    " responses.</p><br>",
                    "<p>There were ", report_information[["IC"]], " 'What could we do better' responses and ", report_information[["BC"]],
                    " 'What did we do well' responses</p><br>",
                    ifelse(report_information[["NFFT"]] > 9,
                           paste0("<p>The Friends and Family Test Score is the proportion of patients
      who are extremely likely or likely to recommend a service. In the selected period of time it was ",
      report_information[["FFT"]], "% (based on ", report_information[["NFFT"]], " responses.)", "</p><br>"), ""),
      ifelse(report_information[["NSQ"]] > 9,
             paste0("<p>Service quality rating was ", report_information[["SQ"]], 
                    "% (based on ", report_information[["NSQ"]],
                    " responses.)</p>"), ""),
      ifelse(sum(report_information[["complaint_numbers"]]) > 3,
             paste0("<p>", report_information[["complaint_numbers"]][3], 
                    " individuals reported that they knew how to make a complaint, ",
                    report_information[["complaint_numbers"]][2], 
                    " reported that they did not know how to make a complaint, and ",
                    report_information[["complaint_numbers"]][1], 
                    " reported that they were unsure if they knew.</p>"), "")
  )
}

cat(myString)

```

## Summary of responses

```{r fig.width=7, fig.height=6, echo=FALSE, warning=FALSE, fig.cap="Percentage of responses", dpi=400}

stack_function(suceData)

```

```{r fig.width=7, fig.height=6, echo=FALSE, warning=FALSE, fig.cap="Trend over time", dpi=400}

trend_function(two_year_data)

```

```{r, results = "asis"}

# produce all the variables and then place them inline below the chunk

returnTopComments <- function(nth_row, type){
  
  if(type == "Improve"){
    
    check1 <- suceData %>% 
      filter(!is.na(Imp1)) %>% 
      left_join(categoriesTable, by = c("Imp1" = "Number")) %>% 
      select(Category, Super)
    
    check2 <- suceData %>% 
      filter(!is.na(Imp2)) %>% 
      left_join(categoriesTable, by = c("Imp2" = "Number")) %>% 
      select(Category, Super)
  }
  
  if(type == "Best"){
    
    check1 <- suceData %>% 
      filter(!is.na(Best1)) %>% 
      left_join(categoriesTable, by = c("Best1" = "Number")) %>% 
      select(Category, Super)
    
    check2 <- suceData %>% 
      filter(!is.na(Best2)) %>% 
      left_join(categoriesTable, by = c("Best2" = "Number")) %>% 
      select(Category, Super)
  }
  
  check_final <- rbind(check1, check2)
  
  count_table <- check_final %>% 
    filter(!is.na(Super), !is.na(Category)) %>% 
    group_by(Category, Super) %>% 
    count() %>% 
    ungroup()
  
  # this is the bit that returns the nth top comment
  
  return_table <- count_table %>% 
    mutate(percent = round(n / sum(n) * 100, 1)) %>% 
    arrange(-percent) %>% 
    slice(nth_row)
  
  # return three comments that are exemplars of that comment
  
  comment_numbers <- return_table %>% 
    left_join(categoriesTable, by = c("Category", "Super")) %>% 
    pull(Number)
  
  if(type == "Improve"){
    
    return_comments <- suceData %>% 
      filter(Imp1 %in% comment_numbers |
               Imp2 %in% comment_numbers) %>% 
      filter(!is.na(Improve)) %>% 
      sample_n(ifelse(nrow(.) >= 3, 3, nrow(.))) %>%  
      pull(Improve) %>% 
      paste0("<p>", 1 : length(.), ": ", ., "</p>", collapse = "")
  }
  
  if(type == "Best"){
    
    return_comments <- suceData %>% 
      filter(Best1 %in% comment_numbers |
               Best2 %in% comment_numbers) %>% 
      filter(!is.na(Best)) %>% 
      sample_n(ifelse(nrow(.) >= 3, 3, nrow(.))) %>%  
      pull(Best) %>% 
      paste0("<p>", 1 : length(.), ": ", ., "</p>", collapse = "")
  }
  
  return(list("return_table" = return_table, 
              "return_comments" = return_comments))
}

```

```{r, results = "asis"}

# do this if they have selected a text summary of comments

if(params$directorate == "NA"){
  
  improve_1 <- returnTopComments(1, "Improve")[["return_table"]]
  
  if(is.null(improve_1)){
    
    cat("Insufficient data for this type of summary.  \n  \n")
  } else {
    
    improve_2 <- returnTopComments(2, "Improve")[["return_table"]]
    improve_3 <- returnTopComments(3, "Improve")[["return_table"]]
    
    cat("## What could we do better?  \n")
    
    cat("The most common comment category was ", 
        paste0(improve_1$Super, ": ", improve_1$Category, paste0(improve_1$percent, "%. ")),
        "Example comments include: ", returnTopComments(1, "Improve")[["return_comments"]])
    
    cat("The second most common comment category was ", 
        paste0(improve_2$Super, ": ", improve_2$Category, paste0(improve_2$percent, "%. ")),
        "Example comments include: ", returnTopComments(2, "Improve")[["return_comments"]])
    
    cat("The third most common comment category was ", 
        paste0(improve_3$Super, ": ", improve_3$Category, paste0(improve_3$percent, "%. ")),
        "Example comments include: ", returnTopComments(3, "Improve")[["return_comments"]], "  \n")
    
  }
  
  best_1 <- returnTopComments(1, "Best")[["return_table"]]
  
  if(is.null(best_1)){
    
    cat("Insufficient data for this type of summary.   \n  \n")
  } else {
    
    cat("## What did we do well?  \n")
    best_2 <- returnTopComments(2, "Best")[["return_table"]]
    best_3 <- returnTopComments(3, "Best")[["return_table"]]
    
    cat("The most common comment category was ", 
        paste0(best_1$Super, ": ", best_1$Category, paste0(best_1$percent, "%. ")),
        "Example comments include: ", returnTopComments(1, "Best")[["return_comments"]])
    
    cat("The second most common comment category was ", 
        paste0(best_2$Super, ": ", best_2$Category, paste0(best_2$percent, "%. ")),
        "Example comments include: ", returnTopComments(2, "Best")[["return_comments"]])
    
    cat("The third most common comment category was ", 
        paste0(best_3$Super, ": ", best_3$Category, paste0(best_3$percent, "%. ")),
        "Example comments include: ", returnTopComments(3, "Best")[["return_comments"]])
    
  }
} else {
  
  do_better <- suceData %>% 
    filter(!is.na(Improve), (Imp1 != 4444 | is.na(Imp1))) %>% 
    mutate(comment_with_location = paste0(Improve, " (", Location, ")")) %>% 
    pull(comment_with_location)
  
  if(length(do_better) > 1000){
    
    cat("Error. Too many comments. Please reduce your selection  \n")
  } else {
    
    cat("## What could we do better?  \n")
    
    number_of_4444 <- suceData %>% filter(Imp1 == 4444) %>% nrow()
    
    cat(str(number_of_4444))

    if(number_of_4444 > 0){
      
      cat(paste0("There were ", number_of_4444, " responses saying that nothing could be improved  \n"))
    }
    
    cat(
      paste0("<p>", do_better, "</p>", collapse = "")
    )
  }
  
  do_well <- suceData %>% 
    filter(!is.na(Best)) %>% 
    mutate(comment_with_location_best = paste0(Best, " (", Location, ")")) %>% 
    pull(comment_with_location_best)

  if(length(do_better) > 1000){
    
    cat("Error. Too many comments. Please reduce your selection  \n")
  } else {
    
    cat("## What did we do well?  \n")
    
    cat(
      paste0("<p>", do_well, "</p>", collapse = "")
    )
  }
}

```

## Team reports- click to download

```{r, results = "asis", message = FALSE}

# this is where if it's a directorate report I'm going to produce
# a set of links that go to all the team reports that exist

if(params$directorate != "NA"){

  team_numbers <- suceData %>%
    group_by(TeamC) %>%
    count() %>%
    filter(n > 2) %>%
    inner_join(counts) %>%
    filter(!duplicated(TeamC)) %>%
    ungroup()

  team_numbers %>%
    mutate(print = paste0("[", TeamN, "](http://suce.co.uk:8000/word?team=", TeamC, ")  \n  \n")) %>%
    pull(print) %>%
    cat()
}

```
