---
title: Comments report
output: html_document
params:
  division: NA
  directorate: NA
  team: NA
  date_from: NA
  date_to: NA
  carerSU: NA
  area_name: NA
  comment_sort: NA
  comment_summary: NA
  filterCommentsBy: NA
  searchTextInclude: NA
  textSearchExclude: NA
  criticalityLevels: NA
  topSixThemes: NA
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# source the code with the functions in

source("../report_functions.R")

report_list <- report_data(division = params$division, directorate = params$directorate, 
                           team = params$team, date_from = params$date_from, date_to = params$date_to, 
                           carerSU = params$carerSU, area_name = params$area_name)

suceData <- report_list[["suceData"]]

```

## What could we do better?

```{r, results = "asis"}

text_df <- returnSearchText(suceData, "Improve",
                            filterCommentsBy = params$filterCommentsBy,
                            searchTextInclude = params$searchTextInclude, 
                            textSearchExclude = params$textSearchExclude,
                            criticalityLevels = params$criticalityLevels, 
                            topSixThemes = params$topSixThemes)

cat(paste0("<p>", text_df$Improve, " (", 
       text_df$Location, ")</p>", collapse = ""))

```

## What did we do well?

```{r, results = "asis"}

text_df <- returnSearchText(suceData, "Best",
                            filterCommentsBy = params$filterCommentsBy,
                            searchTextInclude = params$searchTextInclude, 
                            textSearchExclude = params$textSearchExclude,
                            criticalityLevels = params$criticalityLevels, 
                            topSixThemes = params$topSixThemes)

cat(paste0("<p>", text_df$Improve, " (", 
       text_df$Location, ")</p>", collapse = ""))

```
