---
title: Quarterly report
output: html_document
params:
  team: NA
  carer_su: NA
---

```{r setup, include=FALSE}

library(lubridate)
library(tidyverse)
library(scales)
library(pins)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

connect_key <- readLines("CONNECT_API_KEY")

board_register_rsconnect("SPACED",
                         server = "https://feedbackmatters.uk/rsconnect",
                         key = connect_key)

trustData <- pin_get("trustData", board = "SPACED") %>% 
  mutate(across(all_of(c("Imp1", "Imp2", "Best1", "Best2")), as.character))

# source the code with the functions in

source("../R/report_functions.R", local = TRUE)

```

```{r}

# calculate the date range first

today = Sys.Date()

previous_quarter <- (quarter(today)) - 1 %% 4
previous_year <- year(today)

if(previous_quarter == 0){
  
  previous_quarter <- 4
  previous_year <- previous_year - 1
}

first_date <- yq(paste0(previous_year, ": Q", previous_quarter))

end_date <- yq(paste0(year(today), ": Q", quarter(today))) - 1

# filter by area and name the areas

suceData = trustData %>% 
  filter(TeamC %in% params$team)

# filter by time last and produce another dataset with 2 years in

two_year_data <- suceData %>% 
  filter(Date > end_date - 365 * 2)

suceData <- suceData %>%
  filter(Date >= first_date, Date <= end_date)

if(params$carer_su == "SU"){

  suceData = suceData %>%
    filter(is.na(formtype) | formtype != "SUCE")

} else if(params$carer_su == "carer"){

  suceData = suceData %>%
    filter(formtype == "carer")

} else if(params$carer_su == "bothCarerSU"){

  # nothing!
}

area_name <- suceData %>% 
  pull(TeamN) %>% 
  tail(1)

# generate report information

report_information <- reportFunction(suceData)

```

## Summary

This report summarises data from `r first_date` to `r end_date`. There were `r nrow(suceData)` responses.

```{r, results = "asis"}

if(is.null(report_information)){
  
  myString = "Within the selected time and area there were no responses"
} else {
  
  myString = paste0("<p>Within ", area_name, " in the selected time there were ", report_information[["NR"]],
                    " responses.</p><br>",
                    "<p>There were ", report_information[["IC"]], " 'What could we do better' responses and ", report_information[["BC"]],
                    " 'What did we do well' responses</p><br>",
                    ifelse(report_information[["NFFT"]] > 9,
                           paste0("<p>The Friends and Family Test Score is the proportion of patients
      who are extremely likely or likely to recommend a service. In the selected period of time it was ",
      report_information[["FFT"]], "% (based on ", report_information[["NFFT"]], " responses.)", "</p><br>"), ""),
      ifelse(report_information[["NSQ"]] > 9,
             paste0("<p>Service quality rating was ", report_information[["SQ"]], 
                    "% (based on ", report_information[["NSQ"]],
                    " responses.)</p>"), ""),
      ifelse(sum(report_information[["complaint_numbers"]]) > 3,
             paste0("<p>", report_information[["complaint_numbers"]][3], 
                    " individuals reported that they knew how to make a complaint, ",
                    report_information[["complaint_numbers"]][2], 
                    " reported that they did not know how to make a complaint, and ",
                    report_information[["complaint_numbers"]][1], 
                    " reported that they were unsure if they knew.</p>"), "")
  )
}

cat(myString)

```

```{r fig.width=7, fig.height=6, echo=FALSE, warning=FALSE, fig.cap="Percentage of responses", dpi=400}

if(params$carer_su == "SU"){
  
  if(!is.null(stack_function(suceData, type = "suce_report"))){
  
  stack_function(suceData, type = "suce_report")
  }
}

if(params$carer_su == "carer"){
  
  if(!is.null(stack_function(suceData, type = "carer_report"))){
    
  stack_function(suceData, type = "carer_report")
  }
}

if(params$carer_su == "bothCarerSU"){
  
  if(!is.null(stack_function(suceData, type = "carer_report"))){
  
  stack_function(suceData, type = "suce_dashboard")
  
  stack_function(suceData, type = "carer_dashboard")
  
  }
}

```

```{r fig.width=7, fig.height=6, echo=FALSE, warning=FALSE, fig.cap="Trend over time", dpi=400}

if(params$carer_su == "SU"){
  
  trend_function(two_year_data, type = "suce_report")
}

if(params$carer_su == "carer"){
  
  trend_function(two_year_data, type = "carer_report")
}

if(params$carer_su == "bothCarerSU"){
  
  trend_function(two_year_data, type = "suce_dashboard")
  
  trend_function(two_year_data, type = "carer_dashboard")
}

trend_function(two_year_data)

```

## What could we do better?

```{r, results = "asis"}

cat(
  suceData %>% 
    filter(!is.na(Improve)) %>% 
    pull(Improve) %>% 
    paste0("<p>", ., "</p>", collapse = "")
)

```

## What did we do well?

```{r, results = "asis"}

cat(
  suceData %>% 
    filter(!is.na(Best)) %>% 
    pull(Best) %>% 
    paste0("<p>", ., "</p>", collapse = "")
)

```
